sudo: false

language: ruby

cache: bundler

branches:
  only:
  - gh-pages

before_install:
  - npm install -g pug

install:
  - gem install bundle
  - bundle install

script:
  - JEKYLL_ENV=production jekyll build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: gh-pages
  target-branch: master
  local-dir: _site
  fqdn: diveshuttam.me
